export const listTotal: Object[] = [
	{
		category: 'Alimentation',
		alphabet: [
			{ lettre: 'symbolesChiffres', brand: ['+2Foot'] },
			{ lettre: 'A', brand: ['Alto Café', 'Amorino'] },
			{ lettre: 'B', brand: ['Brasserie Olivium', 'BUBBLE BAR', 'Burger Bar by Quick'] },
			{ lettre: 'C', brand: ['Camarosa', 'Columbus Café', 'Creams Factory', 'Crêpe Touch'] },
			{ lettre: 'F', brand: ['Fresg Factory', 'Columbus Café', 'Creams Factory', 'Crêpe Touch'] },
			{ lettre: 'H', brand: ['Half Time'] },
			{ lettre: 'K', brand: ['KFC'] },
			{ lettre: 'L', brand: ['Le Club Sandwich'] },
			{ lettre: 'M', brand: ['Manhattan’s store', 'Mezzo Di Pasta'] },
			{ lettre: 'O', brand: ["O'Tacos"] },
			{ lettre: 'P', brand: ['Papaya Bar', 'PEPE MANZO', 'Pitaya', 'Pomme de Pain'] },
			{ lettre: 'S', brand: ['Segafredo', 'Subway', 'Sushi Hanaka'] },
			{ lettre: 'V', brand: ['Veng Hour'] },
			{ lettre: 'W', brand: ['Waffle Factory', 'Wok ô King'] },
			{ lettre: 'Y', brand: ['Yogugrt Factory'] },
		],
	},
	{
		category: 'Cosmétique',
		alphabet: [
			{ lettre: 'symbolesChiffres', brand: ['+2Foot'] },
			{ lettre: 'A', brand: ['Adopt'] },
			{ lettre: 'B', brand: ['Bar à S.Cils', 'Body Minute'] },
			{ lettre: 'D', brand: ['Dépil Tech'] },
			{ lettre: 'F', brand: ['Franck Provost'] },
			{ lettre: 'G', brand: ['Générale d’Optique', 'Grand Optical'] },
			{ lettre: 'H', brand: ["HAIR'minute"] },
			{ lettre: 'J', brand: ['Jeff de Bruges'] },
			{ lettre: 'K', brand: ['KIKO'] },
			{ lettre: 'L', brand: ['La Boutique Du Coiffeur'] },
			{ lettre: 'M', brand: ['M-A-C Cosmetics', 'Marionnaud'] },
			{ lettre: 'O', brand: ['Optical Service OS+'] },
			{ lettre: 'P', brand: ['Pharmacie'] },
			{ lettre: 'S', brand: ['Saint Algue', 'Sephora'] },
			{ lettre: 'T', brand: ['The Body Shop', 'Twenty Nails'] },
			{ lettre: 'W', brand: ['Waffle Factory', 'Wok ô King'] },
			{ lettre: 'Y', brand: ['Yves Rocher'] },
		],
	},
	{
		category: 'Décration',
		alphabet: [
			{ lettre: 'A', brand: ['Action'] },
			{ lettre: 'F', brand: ['Flying Tiger Copenhagen'] },
			{ lettre: 'H', brand: ['HEMA'] },
			{ lettre: 'M', brand: ['MUY MUCHO'] },
			{ lettre: 'N', brand: ['Normal'] },
			{ lettre: 'P', brand: ['Pylônes'] },
		],
	},
	{
		category: 'Habillement',
		alphabet: [
			{ lettre: 'A', brand: ['ASICS', 'Au Masculin'] },
			{ lettre: 'B', brand: ['Bershka', 'Biskuit Paris'] },
			{ lettre: 'C', brand: ['Calzedonia', 'Celio', 'CHK', 'CIPO & BAXX'] },
			{ lettre: 'D', brand: ['Devred 1902'] },
			{ lettre: 'E', brand: ['Easy', 'Etam Lingerie'] },
			{ lettre: 'F', brand: ['Foot Korner', 'Foot Locker', 'FORESTLAND'] },
			{ lettre: 'G', brand: ['GUESS'] },
			{ lettre: 'H', brand: ['H&M', 'HUNKEMÖLLER'] },
			{ lettre: 'I', brand: ['Izac'] },
			{ lettre: 'J', brand: ['Jennyfer', 'Jules'] },
			{ lettre: 'K', brand: ['Kaporal', 'Kiabi', 'Kombak'] },
			{ lettre: 'L', brand: ['Lacoste', 'Levi’s'] },
			{ lettre: 'M', brand: ['Mango'] },
			{ lettre: 'N', brand: ['NEW YORKER'] },
			{ lettre: 'O', brand: ['OVS Kids'] },
			{ lettre: 'P', brand: ['Pimkie Primark', 'Pull & Bear'] },
			{ lettre: 'S', brand: ['Salsa', 'Sergent Major', 'Stradivarius'] },
			{ lettre: 'T', brand: ["Tape à l'œil", 'Territoire Redskins'] },
			{ lettre: 'U', brand: ['Undiz'] },
			{ letttre: 'X'['X-CLUSIF'] },
			{ lettre: 'Z', brand: ['ZARA', 'ZELYS'] },
		],
	},
	{
		category: 'MultimédiasJouets',
		alphabet: [
			{ lettre: 'B', brand: ['Bouygues Télécom'] },
			{ lettre: 'F', brand: ['Free'] },
			{ lettre: 'G', brand: ['GIBERT'] },
			{ lettre: 'H', brand: ['Hubside'] },
			{ lettre: 'L', brand: ['La Grande Récré'] },
			{ lettre: 'M', brand: ['Maxxi Games'] },
			{ lettre: 'O', brand: ['Orange'] },
			{ lettre: 'S', brand: ['SFR'] },
		],
	},
	{
		category: 'Services',
		alphabet: [
			{ lettre: 'symbolesChiffres', brand: ['5àsec'] },
			{ lettre: 'A', brand: ['Alter smoke'] },
			{ lettre: 'C', brand: ['Cabinet dentaire', 'COM 9'] },
			{ lettre: 'L', brand: ['La Cordonnerie'] },
			{ lettre: 'P', brand: ['Photomaton', 'Promo Vacances'] },
		],
	},
	{
		category: 'Sport',
		alphabet: [
			{ lettre: 'symbolesChiffres', brand: ['+2foot'] },
			{ lettre: 'A', brand: ['Adidas Originals', 'ASICS'] },
			{ lettre: 'B', brand: ['BioTech USA'] },
		],
	},
];
